//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KBPClassBetaEntities1 : DbContext
    {
        public KBPClassBetaEntities1()
            : base("name=KBPClassBetaEntities1")
        {
        }
        static KBPClassBetaEntities1 context;
        public static KBPClassBetaEntities1 GetContext()
        {
            if (context == null)
            {
                context = new KBPClassBetaEntities1();
            }
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<WorkPlans> WorkPlans { get; set; }
    }
}
