//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int IDTask { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public int IDWorkPlan { get; set; }
    
        public virtual WorkPlans WorkPlans { get; set; }
    }
}
